In [1]:
import numpy as np

In [7]:
heights = np.genfromtxt('heights.txt', delimiter=',')

In [8]:
heights

array([74., 74., 72., ..., 75., 75., 73.])

In [9]:
heights[:5]

array([74., 74., 72., 72., 73.])

In [10]:
heights[-5:]

array([73., 74., 75., 75., 73.])

In [11]:
heights.size

1015

In [12]:
import os
cwd = os.getcwd()
print(cwd)

/Users/tieulyphidao/Desktop/random_code_file/trung_tam_tin_hoc/data_manipulation_visualization


In [13]:
heights = heights * 0.0254

In [14]:
heights

array([1.8796, 1.8796, 1.8288, ..., 1.905 , 1.905 , 1.8542])

In [15]:
f = open('heights.txt')
data = f.read()
f.close()

In [16]:
type(data)

str

In [21]:
heights = np.array(eval(data))

In [22]:
heights

array([74, 74, 72, ..., 75, 75, 73])